---
token:
application_id: 
google_api_key: 
choice_prefixes:
- 'I''m going to go with '
- 'Most certainly '
- 'How about '
- 'I guess I''ll go with '
- 'With out a doubt '
- 'F**king hell it''s '
- 'All signs point to '
predefined_roles:
  admin:
    commands:
    - ban
    - setrole
    options:
      inherit: moderator
      power: 3
  member:
    commands:
    - about
    - choose
    - help
    - ping
    - random
    - time
    - calc
    - radio
    - plugin.list
    options:
      inherit: default
      power: 1
  moderator:
    commands:
    - warn
    - kick
    options:
      inherit: member
      power: 2
  superadmin:
    commands:
    - "*"
    options:
      inherit: admin
      power: 9001
radio_channel: 
restricted_permissions:
- stop
- restart
- eval
- reload
- saveconfig
- plugin.load
- plugin.unload
user_whitelist:
- Evalelynn#3885
