---
token:
application_id:
google_api_key:
radio_channel:
choice_prefixes:
- 'I''m going to go with '
- 'Most certainly '
- 'How about '
- 'I guess I''ll go with '
- 'With out a doubt '
predefined_roles:
    member:
        options:
            inherit: default
            power: 1
        commands:
        - about
        - choose
        - help
        - ping
        - random
        - time
        - calc
        - radio
    moderator:
        options:
            inherit: member
            power: 2
        commands:
        - warn
        - kick
    admin:
        options:
            inherit: moderator
            power: 3
        commands:
        - ban
        - setrole
    superadmin:
        options:
            inherit: admin
            power: 9001
        commands:
        - "*"
restricted_permissions:
- stop
- restart
- eval
- reval
- leave.others
user_whitelist:
- evalelynn#1885
